Load data

In [7]:
from datasets import load_dataset

ds = load_dataset("tomekkorbak/python-github-code", split="test")
ds

Dataset({
    features: ['text', 'repo_name', 'path', 'language', 'license', 'size', 'score'],
    num_rows: 10000
})

Filter executable code

In [ ]:
import sys
sys.path.append("..")

from python_editor.data_filtering import format_df, filter_df

ds.set_format("pandas")
df = ds[:]

df = format_df(df)
df = filter_df(df)

df

,text,repo_name,path,license,NUM_CHARS
0,from __future__ import print_function\r\n\r\ni...,Jeff-Tian/mybnb,Python27/Lib/test/test___all__.py,apache-2.0,4298
1,from __future__ import print_function\nfrom pa...,dssg/wikienergy,disaggregator/build/pandas/pandas/io/tests/tes...,mit,17790
2,"""""""\nOutlier Detection using Tukeys Filter Cla...",trademob/anna-molly,lib/plugins/tukeys_filter.py,mit,5255
3,# Copyright (c) 2018 PaddlePaddle Authors. A...,PaddlePaddle/Paddle,python/paddle/fluid/tests/unittests/xpu/test_r...,apache-2.0,6221
4,# -*- coding: utf-8 -*-\nfrom __future__ impor...,marevol/gym-starter-kit-example,pong/__init__.py,apache-2.0,240
...,...,...,...,...,...
6270,"""""""\nHere we test our output parsing and match...",PKRoma/httpie,tests/utils/matching/test_matching.py,bsd-3-clause,5827
6271,"from __future__ import absolute_import, unicod...",chrxr/wagtail,wagtail/wagtailsearch/tests/test_db_backend.py,bsd-3-clause,854
6272,from lib.action import BaseVMsAction\n\n__all_...,armab/st2contrib,packs/rackspace/actions/set_vm_metadata_item.py,apache-2.0,490
6273,#\n# Licensed to the Apache Software Foundatio...,practice-vishnoi/dev-spark-1,python/pyspark/mllib/__init__.py,apache-2.0,1208
6274,# Copyright 2015 The TensorFlow Authors. All R...,llhe/tensorflow,tensorflow/tools/docs/generate_lib_test.py,apache-2.0,5039

In [9]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()

from python_editor.data_processing import has_executable_code


df["has_executable_code"] = df.progress_apply(has_executable_code, axis=1)
df = df[df["has_executable_code"]]

df

100%|██████████| 6275/6275 [00:05<00:00, 1070.11it/s]

,text,repo_name,path,license,NUM_CHARS,has_executable_code
1,from __future__ import print_function\nfrom pa...,dssg/wikienergy,disaggregator/build/pandas/pandas/io/tests/tes...,mit,17790,True
2,"""""""\nOutlier Detection using Tukeys Filter Cla...",trademob/anna-molly,lib/plugins/tukeys_filter.py,mit,5255,True
3,# Copyright (c) 2018 PaddlePaddle Authors. A...,PaddlePaddle/Paddle,python/paddle/fluid/tests/unittests/xpu/test_r...,apache-2.0,6221,True
4,# -*- coding: utf-8 -*-\nfrom __future__ impor...,marevol/gym-starter-kit-example,pong/__init__.py,apache-2.0,240,True
5,import re\n\nfrom tornado.escape import xhtml_...,JmPotato/College,handlers/utils.py,mit,2237,True
...,...,...,...,...,...,...
6270,"""""""\nHere we test our output parsing and match...",PKRoma/httpie,tests/utils/matching/test_matching.py,bsd-3-clause,5827,True
6271,"from __future__ import absolute_import, unicod...",chrxr/wagtail,wagtail/wagtailsearch/tests/test_db_backend.py,bsd-3-clause,854,True
6272,from lib.action import BaseVMsAction\n\n__all_...,armab/st2contrib,packs/rackspace/actions/set_vm_metadata_item.py,apache-2.0,490,True
6273,#\n# Licensed to the Apache Software Foundatio...,practice-vishnoi/dev-spark-1,python/pyspark/mllib/__init__.py,apache-2.0,1208,True
6274,# Copyright 2015 The TensorFlow Authors. All R...,llhe/tensorflow,tensorflow/tools/docs/generate_lib_test.py,apache-2.0,5039,True

Create and save a 100 rows sample

In [10]:
df_sample = df.sample(100)
df_sample

,text,repo_name,path,license,NUM_CHARS,has_executable_code
3703,class MsgBundle(object):\n\n JOB_TEMPLATE_M...,rombie/contrail-controller,src/config/fabric-ansible/job_manager/job_mess...,apache-2.0,9679,True
3140,from __future__ import unicode_literals\nfrom ...,michaelBenin/pep8ify,pep8ify/fixes/fix_missing_newline.py,apache-2.0,1018,True
5436,"# Copyright 2016-2017 Capital One Services, LL...",jdubs/cloud-custodian,tests/test_appelb.py,apache-2.0,14379,True
4043,from __future__ import absolute_import\nfrom _...,pratikgujjar/DeepIntent,code/autoencoder_model/scripts/attention_autoe...,mit,20029,True
2330,"# -*- coding: utf-8 -*-\n""""""Init and utils.""""""...",a25kk/dakhli,src/dakhli.sitecontent/dakhli/sitecontent/__in...,mit,222,True
...,...,...,...,...,...,...
2568,"import os\n\n\nINSTALLED_APPS = (\n ""django...",feincms/feincms-elephantblog,tests/testapp/settings.py,bsd-3-clause,2354,True
6254,# -*- coding: utf-8 -*-\nfrom __future__ impor...,ohmini/thaifoodapi,thaifood/migrations/0001_initial.py,bsd-3-clause,10416,True
4926,# ***** BEGIN LICENSE BLOCK *****\n# Version: ...,kpkhxlgy0/SublimeText3,Packages/SublimeCodeIntel/SublimeCodeIntel.py,mit,49980,True
2490,"# Copyright (c) 2011 Duncan Fordyce, Jimmy Cao...",Agent-Isai/lykos,oyoyo/client.py,bsd-2-clause,11881,True
976,"from setuptools import (\n setup,\n find...",catapult-project/catapult,third_party/beautifulsoup4-4.9.3/setup.py,bsd-3-clause,1713,True

In [11]:
df_sample.to_csv("../data/test_sample.csv", index=False)